### ISSUE TITLE
"Thread crashed" when running A3CCartpole example

### ISSUE THREAD

**Issue by howard-abrams** [deeplearning4j/rl4j#19]
When running the A3CCartpole example, after a short time (under 1 min), the application will stop "Thread Crash" and "Connection Error" exceptions on each thread. Setting render to "true" just delays the termination. It can be seen from the rendered windows that everything seems to be working up until it doesn't. 

See logs:
https://gist.github.com/howard-abrams/cdaf8fb0dbff20adc1a6f40e9400d3ed
https://gist.github.com/howard-abrams/5cad4816f4c056db3161725bb086f79b

Note: Seems like in the last comment of https://github.com/deeplearning4j/rl4j/issues/11 Mark had the same issue. Not sure if he got past it somehow.

**Comment by saudet** [comment]
I ran into this issue, and this is actually caused by Flask as used by gym-http-api. The only viable workaround that I found after spending a couple of hours debugging that is executing this command beforehand (or doing its equivalent):
```bash
$ sudo sysctl -w net.ipv4.tcp_tw_recycle=1
```
In theory, we should be able to get this working better using the following line before `app.run()` in `gym_http_server.py`, but then gym-http-api fails to parse the JSON messages for some reason.
```python
    WSGIRequestHandler.protocol_version = "HTTP/1.1"
```
Since this is actually a problem with gym-http-api, be sure to report the issue there if this workaround isn't satisfactory: https://github.com/openai/gym-http-api/issues
