### ISSUE TITLE
rl4j & cuda

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#42]
Is it possible to enable cuda backend with rl4j? As far as I understand it it should be fairly straightforward for DQN but not so much for A3C.

**Comment by saudet** [comment]
It should work, yes. If you could try it out as it is now and report your
findings, it would help!

**Comment by saudet** [comment]
I've just tried it with the CUDA backend, and it works fine, but very slowly because of getDouble() and putScalar() operations here:
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/learning/sync/qlearning/discrete/QLearningDiscrete.java#L207
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/learning/async/AsyncThreadDiscrete.java#L107
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/learning/async/a3c/discrete/A3CThreadDiscrete.java#L75

We'll need to do something about that...

**Comment by saudet** [comment]
Actually, at the moment, most of the time seems to be spent in concat() operations...

**Comment by saudet** [comment]
Ok, fixed, DQN works well now with this: https://github.com/deeplearning4j/rl4j/commit/63adcf02980cf8baea395adf1bb333ec0ed57c21

I'm not sure if we can get async to work well at all, but it might work well just by setting the device affinity as with ParallelWrapper: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-scaleout-parallelwrapper/src/main/java/org/deeplearning4j/parallelism/ParallelWrapper.java#L133

You would mind giving this a try?

**Comment by raver119** [comment]
Side note: concat perf was improved, merge incoming: https://github.com/deeplearning4j/nd4j/issues/1845

**Comment by ecthx** [comment]
So I did couple of basic tests and it seems to work with both DQN and A3C.  I see less cpu load and more GPU utilization. 
For reference I will post a link to a interesting paper about hybrid CPU&GPU A3C. It takes a different approach and I'm not sure if its relevant to rl4j or dl4j.

[https://arxiv.org/abs/1611.06256](url)
[https://github.com/NVlabs/GA3C](url)

**Comment by saudet** [comment]
Hybrid, we'd first need to implement that in ND4J :)

**Comment by saudet** [comment]
Although the architecture is different. It's training only one model, so it might be possible without any changes to ND4J.

**Comment by agibsonccc** [comment]
@saudet you got this working didn't you?

**Comment by saudet** [comment]
Yes, it basically works. I've also added the affinity bit in commit https://github.com/deeplearning4j/rl4j/commit/bc1e6fb1bfac5e4d265412e751f4adacee5ab9ac so it'll work well as long as we have enough GPU devices.
